import os
import math
import numpy as np
import pandas as pd

# ==========================================================
# INPUT / OUTPUT PATHS
# ==========================================================
# NFSTREAM_CSV
# ├── Benign_Final
# ├── DDoS-TCP_Flood
# ├── ...
#
# Each folder contains multiple NFStream CSV files
#
# BALANCED_ATTACKS
# ├── Benign_Final.csv
# ├── DDoS-TCP_Flood.csv
# ├── ...
#
# Each output file contains exactly 60,000 sampled rows
# ==========================================================


ROOT_DIR = "NFSTREAM_CSV"
OUTPUT_DIR = "BALANCED_ATTACKS"

# Number of rows required for each attack class
TARGET_ROWS = 60000

# Read large CSV files in chunks to reduce RAM usage
CHUNK_SIZE = 100000

# Fixed seed for reproducibility
RANDOM_STATE = 42

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ==========================================================
# COLUMNS TO REMOVE
#
# These columns are removed because:
# - identifiers
# - IP addresses
# - MAC addresses
# - application names
# - timestamps
# - ports
#
# can cause overfitting and do not represent attack behaviour
# ==========================================================
# COLUMNS REMOVED BEFORE BALANCING
# ==========================================================
#
# These columns are removed because they are:
#
# 1. Identifiers
#    - Do not describe attack behaviour
#    - Cause overfitting
#
# 2. IP / MAC Information
#    - Environment dependent
#    - Different in real deployments
#
# 3. Timestamp Features
#    - Absolute timestamps are useless
#    - Model should learn traffic behaviour
#
# 4. Port Numbers
#    - Source/Destination ports change in real traffic
#    - Not robust for deployment
#
# 5. Application Metadata
#    - Generated by DPI
#    - Dataset dependent
#    - Not behavioural
#
# Final IDS uses only behavioural flow features.
#
# ==========================================================

DROP_COLUMNS = [

    # -------------------------
    # Flow Identifiers
    # -------------------------
    "id",
    "expiration_id",

    # -------------------------
    # IP Information
    # -------------------------
    "src_ip",
    "dst_ip",

    # -------------------------
    # MAC Information
    # -------------------------
    "src_mac",
    "dst_mac",

    "src_oui",
    "dst_oui",

    # -------------------------
    # Network Metadata
    # -------------------------
    "vlan_id",
    "tunnel_id",

    # -------------------------
    # Ports
    # -------------------------
    "src_port",
    "dst_port",

    # -------------------------
    # Absolute Timestamps
    # -------------------------
    "bidirectional_first_seen_ms",
    "bidirectional_last_seen_ms",

    "src2dst_first_seen_ms",
    "src2dst_last_seen_ms",

    "dst2src_first_seen_ms",
    "dst2src_last_seen_ms",

    # -------------------------
    # Application Metadata
    # -------------------------
    "application_name",
    "application_category_name",

    "application_is_guessed",
    "application_confidence",

    "requested_server_name",
    "client_fingerprint",
    "server_fingerprint",
    "user_agent",
    "content_type"
]

# ==========================================================
# ATTACK CLASSES USED IN FINAL DATASET
#
# Each attack will finally contribute:
# 60,000 rows
#
# Final Dataset:
# 14 classes × 60,000 rows
# = 840,000 rows
# ==========================================================

ATTACKS = [
    "Benign_Final",

    "DDoS-ICMP_Flood",
    "DDoS-SYN_Flood",
    "DDoS-TCP_Flood",
    "DDoS-UDP_Flood",

    "DoS-SYN_Flood",
    "DoS-TCP_Flood",
    "DoS-UDP_Flood",

    "Recon-HostDiscovery",
    "Recon-PortScan",
    "Recon-OSScan",

    "Mirai-greeth_flood",
    "Mirai-greip_flood",
    "Mirai-udpplain"
]

# ==========================================================
# COUNT NUMBER OF DATA ROWS IN A CSV FILE
#
# Used to calculate proportional sampling ratio
# ==========================================================

def count_rows(csv_path):

    return sum(
        1 for _ in open(
            csv_path,
            encoding="utf-8",
            errors="ignore"
        )
    ) - 1


# ==========================================================
# PROCESS EACH ATTACK CATEGORY
#
# Example:
# Benign_Final
# DDoS-TCP_Flood
# Mirai-udpplain
# ...
# ==========================================================

for attack in ATTACKS:

    print("\n" + "=" * 80)
    print("ATTACK :", attack)
    print("=" * 80)

    # ------------------------------------------------------
    # Locate attack folder
    # ------------------------------------------------------

    attack_path = os.path.join(
        ROOT_DIR,
        attack
    )

    # ------------------------------------------------------
    # Get all CSV files inside attack folder
    # ------------------------------------------------------

    csv_files = sorted([
        f for f in os.listdir(attack_path)
        if f.endswith(".csv")
    ])

    file_rows = {}
    attack_total_rows = 0

    # ------------------------------------------------------
    # Count rows present in every CSV file
    # ------------------------------------------------------

    for file in csv_files:

        path = os.path.join(
            attack_path,
            file
        )

        rows = count_rows(path)

        file_rows[file] = rows

        attack_total_rows += rows

    print(
        f"Total Rows : {attack_total_rows:,}"
    )

    # ------------------------------------------------------
    # Calculate proportional allocations
    # ------------------------------------------------------

    allocations = {}

    allocated_total = 0

    for file in csv_files:

        rows = file_rows[file]

        alloc = round(
            (rows / attack_total_rows)
            * TARGET_ROWS
        )

        allocations[file] = alloc

        allocated_total += alloc

    # ------------------------------------------------------
    # Correct rounding error
    # ------------------------------------------------------

    diff = TARGET_ROWS - allocated_total

    first_file = csv_files[0]

    allocations[first_file] += diff

    attack_parts = []

    # ------------------------------------------------------
    # Process every CSV file individually
    # ------------------------------------------------------

    for file in csv_files:

        path = os.path.join(
            attack_path,
            file
        )

        target = allocations[file]

        print(
            f"{file:<35}"
            f"{file_rows[file]:>12,}"
            f"{target:>12,}"
        )

        sampled_chunks = []

        for chunk in pd.read_csv(
            path,
            chunksize=CHUNK_SIZE,
            low_memory=False
        ):

            # Remove unwanted columns
            chunk.drop(
                columns=DROP_COLUMNS,
                errors="ignore",
                inplace=True
            )

            # Replace Inf values
            chunk.replace(
                [np.inf, -np.inf],
                np.nan,
                inplace=True
            )

            frac = target / file_rows[file]

            sample_n = math.ceil(
                len(chunk) * frac
            )

            sample_n = min(
                sample_n,
                len(chunk)
            )

            sampled_chunk = chunk.sample(
                n=sample_n,
                random_state=RANDOM_STATE
            )

            sampled_chunks.append(
                sampled_chunk
            )

        file_df = pd.concat(
            sampled_chunks,
            ignore_index=True
        )

        if len(file_df) > target:

            file_df = file_df.sample(
                n=target,
                random_state=RANDOM_STATE
            )

        attack_parts.append(
            file_df
        )

    # ------------------------------------------------------
    # Merge sampled files
    # ------------------------------------------------------

    attack_df = pd.concat(
        attack_parts,
        ignore_index=True
    )

    if len(attack_df) > TARGET_ROWS:

        attack_df = attack_df.sample(
            n=TARGET_ROWS,
            random_state=RANDOM_STATE
        )

    # ------------------------------------------------------
    # Add label
    # ------------------------------------------------------

    attack_df["label"] = attack

    # ------------------------------------------------------
    # Save attack CSV
    # ------------------------------------------------------

    save_path = os.path.join(
        OUTPUT_DIR,
        attack + ".csv"
    )

    attack_df.to_csv(
        save_path,
        index=False
    )

    print(
        f"\nFinal Shape : {attack_df.shape}"
    )

    print(
        f"Saved : {save_path}"
    )

# ==========================================================
# COMPLETED
# ==========================================================

print("\nDONE")